### ISSUE TITLE
lighttpd error 500 on actions.php and buttons.php

### ISSUE THREAD

**Issue by seagullmania** [gumslone/GumCP#11]
As the title suggests, im using lighttpd and i'm getting error 500 on the 2 pages. i've no clue how to fix this.

**Comment by gumslone** [comment]
php ssh2 library is not installed
try: 
```sudo apt-get install php-ssh2```
or
```sudo apt-get install php5-ssh2```
depends on php version that you use
after its installed restart the lighthttpd service

**Comment by TT-SWP13** [comment]
I get the same error with nginx and php7.

`php -m | grep ssh`
`ssh2`

`php5 -m | grep ssh`
`ssh2`

`sudo service nginx restart`

In use of php5 i can open both pages.

**Comment by gumslone** [comment]
i have GumCP working well with php 7  too.
try this:
For PHP 7:

`sudo apt-get install php7.0-ssh2`
For PHP 7.1:
`sudo apt-get install php7.1-ssh2`
Restart Apache2 server
`sudo service apache2 restart`
