### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by kavehmollaei** [gumslone/GumCP#14]
Hi 
it is not work for me
whats means make your changes to your /include/config.php file.
what changes in /include/config.php ?

**Comment by gumslone** [comment]
Hi, could you be more specific whats not working?
in config you have to define all the parameters you need, i.e. activate login page, define ssh login and password, activate modules.

**Comment by kavehmollaei** [comment]
Hi
I can not install php5-ssh2

**Comment by kavehmollaei** [comment]
I
Hi
I can not install php5-ssh2

my os is rasbian
can I install php-ssh2  ?

**Comment by gumslone** [comment]
did you install php5 or php7 ?

you could try this command:
`sudo apt-get install php-ssh2`

**Comment by kavehmollaei** [comment]
I install it after step by step
I see this

**Comment by kavehmollaei** [comment]
I install php-ssh2  but could not
install php5-ssh2
It work only php5 and php7?

**Comment by gumslone** [comment]
well it should work? reboot raspberry and check the actions page, if the page is opening then everything is fine.

**Comment by kavehmollaei** [comment]
I reboot raspberry but the page not open

**Comment by kavehmollaei** [comment]
my browser is chrom and after type 192.168.2.247/GumCP/index.php in this
browser came this page
in attached

**Comment by gumslone** [comment]
unfortunately i cant see any attachments, github doesn't show them, you can attach it directly in the github issue

**Comment by kavehmollaei** [comment]
![a](https://user-images.githubusercontent.com/35415391/39694374-5a5a9370-51fc-11e8-8db8-73e9f943c9dd.png)

attached

**Comment by gumslone** [comment]
looks like php is not installed, well you can use any online tutorial how to install apache webserver and php, even from official raspberry pi page: https://www.raspberrypi.org/documentation/remote-access/web-server/apache.md

**Comment by kavehmollaei** [comment]
![b](https://user-images.githubusercontent.com/35415391/39716259-10efc982-5245-11e8-8812-dc1d6f897f7e.png)


I have this page but it is not true I think

**Comment by kavehmollaei** [comment]
![c](https://user-images.githubusercontent.com/35415391/39716677-39fecf3e-5246-11e8-8f74-71395f41f1ab.png)

**Comment by gumslone** [comment]
yes, it shows html and php code, 
the php code shouldn't be visible, it should be executed as a backend script, in your case its showing it as frontend, meaning that the php library is not working, not installed or not added as module to apache web server.

**Comment by gumslone** [comment]
other problem could be that the php files of GumCP are not executable, check the read write permission of the files.

**Comment by kavehmollaei** [comment]
gumcp files?

**Comment by kavehmollaei** [comment]
all files? it is very  HARD in GUMCP folder is many file

**Comment by kavehmollaei** [comment]
I went step by step but I donot khnow why occure this happend

**Comment by gumslone** [comment]
create a **test.php** file in /var/www/html/
put this content to it:
`<?php 
phpinfo(); 
?>`

and try to open it with your browser like http://raspi_ip/test.php

if you will see the contents of the file, it means that php is not installed, if you will see a page with php details like:
![this-is-what-a-phpinfo-file-loos-like](https://user-images.githubusercontent.com/12110353/39728483-ef1c2308-525f-11e8-96f9-1d383eea20ce.gif)
then php is installed.

to install php use this:
`sudo apt-get install php libapache2-mod-php -y`
and restart apache:
`sudo service apache2 restart`

**Comment by kavehmollaei** [comment]
sudo apt-get install php libapache2-mod-php -y

**Comment by kavehmollaei** [comment]
sudo apt-get install php libapache2-mod-php -y

I type this but noy installed

**Comment by kavehmollaei** [comment]
this message come to me
unable to locate package php

**Comment by kavehmollaei** [comment]
I dissapointed install it
thanks

**Comment by gumslone** [comment]
try before installing the packages
`sudo apt update`
you can also try to do
`sudo apt install php7.0 libapache2-mod-php -y` or `sudo apt-get install php7.1 libapache2-mod-php -y` instead of `sudo apt-get install php libapache2-mod-php -y`

**Comment by kavehmollaei** [comment]
i do sudo apt update


but sudo apt install php7.0 libapache2-mod-php -y or sudo apt-get install
php7.1 libapache2-mod-php -y do not

**Comment by kavehmollaei** [comment]
![problem](https://user-images.githubusercontent.com/35415391/39783491-7f217e38-532a-11e8-88b6-83f3e80952e1.jpg)
I have this ....

**Comment by gumslone** [comment]
did you also try to run in with recommended --fix-broken?
like:
`sudo apt-get --fix-broken install php libapache2-mod-php -y`

**Comment by kavehmollaei** [comment]
not working
