### ISSUE TITLE
CPU Usage on Dashboard doesnt change

### ISSUE THREAD

**Issue by akeilox** [gumslone/GumCP#16]
First of all a big thank you for sharing this, exactly what I was looking for to quickly get a raspberry control panel.

In my install on stretch with php7, all seems to work but the CPU dial always stuck at 2% regardless of the top output below (or from console) showing 217% or 180% cpu usage for a python app.

This doesnt seem to change upon manual refresh of the page, or the built-in realtime update for temperature etc dials.

Is this a bug or looking for a specific process ?

**Comment by gumslone** [comment]
Hi,
this is the line responcible for cpu usage in index.php:
`$cpuusage = 100 - shell_exec("vmstat | tail -1 | awk '{print $15}'");`
you could also replace it with:
`$load = sys_getloadavg();
$cpuusage = $load[0];`

please check if it would show the same data.
