### ISSUE TITLE
Not able to upload files using the file manager

### ISSUE THREAD

**Issue by punyanagari** [gumslone/GumCP#18]
Hi. Thank you for this amazing project. I tried to upload files, the browser shows the uploading progress. When it reaches 100% nothing happens.

Thanks again.

**Comment by gumslone** [comment]
hello, php script should have permission to upload to a specific folder, you can chmod the folder to 0777 via command, but its not recommended for every folder or add the script to sudoers with visudo.

**Comment by punyanagari** [comment]
I gave the permissions. I have realised it's not uploading files more than 10-15 MBs.

**Comment by gumslone** [comment]
Check your php.ini file and change the upload_max_filesize and post_max_size value

**Comment by punyanagari** [comment]
Yes found the issue thanks!
