### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [gumslone/GumCP#23]
How to uninstall?

**Comment by gumslone** [comment]
Hi, just delete the GumCP directory

**Comment by ChocolateLoverRaj** [comment]
Is it `/var/www/html`?

**Comment by gumslone** [comment]
yes it should be in /var/www/html/

**Comment by ChocolateLoverRaj** [comment]
What about `apt-get install`s in the install script. Will those be marked as no longer needed so I can just do `sudp apt autormove`?
https://github.com/gumslone/GumCP/blob/78f6a9401e2f2d8d546eef5d44b915a866c6117d/installer.sh#L21
