### ISSUE TITLE
RAM is not visible on the webUI

### ISSUE THREAD

**Issue by Andrewer11** [gumslone/GumCP#4]
The memory says "NAN % REAL MEMORY"
and in the table says "Real memory: MB total / MB used"
What i need to do?

Printscreen: 
![Image of Yaktocat](http://i.imgur.com/oPJZzKx.png?1)
BTW i love GumCP easy2install and lightweight panel!

**Comment by gumslone** [comment]
Hello,
what does the top processes block show? 
Can you make a screenshot?
![screenshot 2017-08-07 12 06 40](https://user-images.githubusercontent.com/12110353/29020022-3fde055a-7b69-11e7-94f1-37f096fed5c0.png)
Thanks

**Comment by hefistion** [comment]
the same problem in raspbian stretch, the free -mo command does not exist
![screenshot-2017-9-16 gumcp dashboard](https://user-images.githubusercontent.com/6677900/30511683-aaa6407a-9ade-11e7-8211-e19c061d11c0.png)

Thanks
