### ISSUE TITLE
 php5-ssh2

### ISSUE THREAD

**Issue by iwenbin** [gumslone/GumCP#5]
i try to install php5-ssh2,but "E: Package 'php5-ssh2' has no installation candidate",how should i do next?
my systeminfo "Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
"  Thank you!

> sudo apt-get install apache2 php5 php5-ssh2
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
Package php5-ssh2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php5-ssh2' has no installation candidate

**Comment by gumslone** [comment]
Hello,
you could try to install it with this command:
`sudo apt-get install libssh2-1-dev libssh2-php `

**Comment by iwenbin** [comment]
thank you very much. the problem is soved!
but i login on ### http://192.168.1.72/GumCP/index.php
it just show ##Welcome to nginx!   
and nothing.
what's step i had wrong?

**Comment by gumslone** [comment]
why nginx? you need apache for it. Anyway if nginx has enabled php, you should upload the files to the web directory of nginx, it might be different than apache.

**Comment by iwenbin** [comment]
Sorry. I can't understand your mean!
And wht's the meaning of   ###  make your changes to your /include/config.php ### 
How can i do?
I am fresh man. 
thank you very much!

**Comment by gumslone** [comment]
nginx is a different type of web server, gumcp was tested and created with apache server, so i have no experience with nginx, cant support you in this case. In the file config.php you can define your password and username for login.

**Comment by iwenbin** [comment]
Awesome! I have got it!  Thank you very much!
In fact, I deleted the GumCP and downloaded it again
