### ISSUE TITLE
Realtime.

### ISSUE THREAD

**Issue by luizoti** [gumslone/GumCP#7]
Hi,

Is it possible to add a WebGui real-time update function?

Thx...

**Comment by gumslone** [comment]
sure, but it may use many system resources, depends on data which you would like to be updated and how often. What data would you line to be realtime?

**Comment by luizoti** [comment]
The bars with as system statistics (CPU LOAD, TEMPERATURE and etc.) and System Processes tab.

**Comment by gumslone** [comment]
will add this in next update

**Comment by luizoti** [comment]
Thanks...

**Comment by gumslone** [comment]
real time functionality is added
