### ISSUE TITLE
Real memory negative

### ISSUE THREAD

**Issue by hefistion** [gumslone/GumCP#8]
![screenshot-2017-10-2 gumcp dashboard](https://user-images.githubusercontent.com/6677900/31060757-21ff300a-a719-11e7-8e53-58adeb808d4d.png)

thanks

**Comment by gumslone** [comment]
is this happening with the latest update?

**Comment by hefistion** [comment]
yes,, your last update, in raspbian  stretch

thanks

**Comment by gumslone** [comment]
can yo make a screenshot of top processes with memory usage, like this:
![29020022-3fde055a-7b69-11e7-94f1-37f096fed5c0](https://user-images.githubusercontent.com/12110353/31152393-8a38651a-a8a4-11e7-84ef-7701d80bbe66.png)

**Comment by hefistion** [comment]
of course
![screenshot-2017-10-4 gumcp dashboard](https://user-images.githubusercontent.com/6677900/31171976-11402a0e-a902-11e7-98a9-bc44764e91e6.png)
thanks

**Comment by gumslone** [comment]
my version of top shows used before free,
your version shows free before used, will try to find a solution that will work for all.

**Comment by gumslone** [comment]
hello, i have updated the index.php file with a fix, can you test it?
thanks

**Comment by hefistion** [comment]
hello, thank you for your work, continue with errors

![screenshot-2017-10-4 gumcp dashboard](https://user-images.githubusercontent.com/6677900/31200730-68c67454-a95c-11e7-80a8-29d4faaa7722.png)
![screenshot-2017-10-4 gumcp dashboard 1](https://user-images.githubusercontent.com/6677900/31200731-68c7bd6e-a95c-11e7-92d5-1ab48b554d1a.png)

regards

**Comment by gumslone** [comment]
this is how its calculated:
round(($memory_used - $memory_buffers - $memory_cached) / $memory_total * 100);
((479836-238424-168020)/766872)*100 = 9.57 its about 10% when rounded
https://unix.stackexchange.com/questions/152299/how-to-get-memory-usedram-used-using-linux-command
what does the 
`free | awk 'FNR == 3 {print $3/($3+$4)*100}'`
 command show as output when you execute it in the actions tab?

**Comment by hefistion** [comment]
all tabs work except the actions tab

running from the terminal
`
  free | awk 'FNR == 3 {print $ 3 / ($ 3 + $ 4) * 100}'`
`
3.60561`

If I execute

```
free | ($, $ 3, $ 4, $ 4, $ 4, $ 4, $ 4, $ 4, $ 4, $ 4 ) * 100} / Swap / {printf (", swap:% .2f%"), $ 3 / $ 2 * 100} '

used: 48.61%, swap: 3.62% c
```

just is happening with the verion strecht with the previous version of the system worked perfect

**Comment by gumslone** [comment]
the previous version has used `free -mo` command which didn't work with all raspberries too :)
actions tab should work with php-ssh2 installed,
anyway, ill try to find a solution which will work for all.

**Comment by juliocoliveira** [comment]
This issue still persists.
I just changed the $memory_percentage to ``` $memory_percentage = round($memory_used / $memory_total * 100, 2); ```
And removed the "o" from free -mo ```$out = shell_exec('free -mo');``` to ```$out = shell_exec('free -m');```
