### ISSUE TITLE
Ubuntu MATE & Contol Panel

### ISSUE THREAD

**Issue by Colink02** [gumslone/GumCP#9]
Is it possible to run this Control Panel on Ubuntu MATE with the pi?

**Comment by gumslone** [comment]
the php script would run, you need apache with php and php-ssh2 modules to be installed,
not sure about the linux commands Ubuntu Mate, if those are the same, it should work too.

**Comment by Colink02** [comment]
ok sweet thanks

**Comment by Colink02** [comment]
Those that want to do this on ubuntu mate on raspberry pi you will need php7.0 instead of php5
sudo apt-get install php7.0 worked for me.
